name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          .pytest_cache
          venv
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install virtualenv
        python -m virtualenv venv
        source venv/bin/activate
        pip install -r requirements.txt
        pip install -e .
        pip install pytest pytest-cov
    - name: Run tests
      run: |
        source venv/bin/activate
        pytest --junitxml=pytest.xml --cov=infsim --cov-report term-missing --cov-fail-under 100
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: pytest.xml
        retention-days: 7

  style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Run pre-commit checks
      run: |
        pip install pre-commit
        pre-commit run --all
